apiVersion: config.istio.io/v1alpha1
kind: RouteRule
metadata:
  namespace: mynamespace
  name: myrouterule
spec:
  destination:
    name: mywebsample
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 100

