apiVersion: v1
data:
  wsid: ${WSID}
  key: ${KEY}
kind: Secret
metadata:
  annotations:
  name: loganalytics-params
  namespace: default
  selfLink: /api/v1/namespaces/mynamespace/secrets/mysecret
type: Opaque
