apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: mynamespace
data:
  SASL: c2hpbmdvLm1zOm1zbXMyMDE2Cg==
  SLACK_URI: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVEM4TVJHVjZDL0JDOE1WNEFMUS9lNkJjUDZ3cVJwa3hkRThzMm92NWdMUDk=
  MONGODB_URI: bW9uZ29kYjovL2s4cy1hcHBzLW1vbmdvZGI6aWpqUFY0TUxJQkU3RlByWUZzbHZiRUFMTXJNRHpaRXdIb2JNdVRMSFNndXpicGphSWViaVVFQ0dXSGxLR0N2ZWNPcHFBc21YSEQwRTI0WjlWVDhJMEE9PUBrOHMtYXBwcy1tb25nb2RiLmRvY3VtZW50cy5henVyZS5jb206MTAyNTU=
