---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: myappsample
  name: myappsample
  namespace: mynamespace
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
    name: http
  selector:
    run: myappsample
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mynotifypod
  name: mynotifypod
  namespace: mynamespace
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
    name: http
  selector:
    app: mynotifypod
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mywebsample
  name: mywebsample
  namespace: mynamespace
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
    # This is the important config.
    # We need to specify the name which start 'http' and some.
    # ref: https://github.com/istio/issues/issues/83
    name: http
  selector:
    run: mywebsample
  sessionAffinity: None
  type: LoadBalancer
